name: nytaxi-project
services:
  db:
    image: docker.io/library/postgres:18
    restart: on-failure
    container_name: ${PG_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PG_HOST_PORT}:${PG_CONTAINER_PORT}"
    volumes:
      # - ./data/init-scripts:/docker-entrypoint-initdb.d/
      - pg-data:/var/lib/postgresql/
    networks:
      - pgnetwork

  db_admin:
    image: docker.io/dpage/pgadmin4
    restart: on-failure
    container_name: ${PGADMIN_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ${PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED}
    ports:
      - "${PGADMIN_HOST_PORT}:${PGADMIN_CONTAINER_PORT}"
    volumes:
      - ${SQL_SCRIPT_PATH}:/var/lib/pgadmin/storage/
    depends_on:
      - db
    networks:
      - pgnetwork

volumes:
  pg-data: {}
networks:
  pgnetwork: {}
